services:
  react-native-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-native-note-app
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
