services:
  react-native-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-native-note-app
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
    restart: unless-stopped
    command: npm start

  # Backend API (jika menggunakan backend terpisah)
  api:
    image: node:16-alpine
    container_name: notes-api
    working_dir: /api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
      - /api/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - app-network
    restart: unless-stopped
    command: npm start

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
